version: '3.9'

volumes:
  postgres:

services:
  postgres:
    image: postgres:13
    tty: true
    restart: on-failure
    command: postgres -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track_utility=off
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U stat_test_task -d stat_test_task
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      POSTGRES_USER: stat_test_task
      POSTGRES_PASSWORD: stat_test_task
      POSTGRES_DB: stat_test_task
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    image: ${DOCKER_REPOSITORY}/${APP_NAME}-helper:${VERSION}
    command: go run ./cmd/server.go
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - configs/env.example
    volumes:
      - ./:/app

  helper:
    image: ${DOCKER_REPOSITORY}/${APP_NAME}-helper:${VERSION}
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - configs/env.example
    volumes:
      - ./:/app