// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/repositories/pgstat/pgstat.go

// Package pgstatrepomocks is a generated GoMock package.
package pgstatrepomocks

import (
	context "context"
	reflect "reflect"

	models "github.com/radon1/pg-stat-test-task/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindQueriesStat mocks base method.
func (m *MockRepository) FindQueriesStat(ctx context.Context, limit, offset int, queryFilters []string) ([]models.QueryStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindQueriesStat", ctx, limit, offset, queryFilters)
	ret0, _ := ret[0].([]models.QueryStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindQueriesStat indicates an expected call of FindQueriesStat.
func (mr *MockRepositoryMockRecorder) FindQueriesStat(ctx, limit, offset, queryFilters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindQueriesStat", reflect.TypeOf((*MockRepository)(nil).FindQueriesStat), ctx, limit, offset, queryFilters)
}
